apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.Values.appName}}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Davidh120/{{.Values.appName}}-k8s.git
    path: "."
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: app-test
