apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.appName}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.appName}}
  minReplicas: {{.Values.spec.minReplicas}}
  maxReplicas: {{.Values.spec.maxReplicas}}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70