apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-rest-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Davidh120/python-rest-api-chart/tree/main
    path: "."
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: app-test
