apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-rest-api
  namespace: argocd
spec:
  project: default
  source:
    chart: desarrollo
    repoURL: https://github.com/Davidh120/python-rest-api-chart.git
    path: ./desarrollo
    targetRevision: HEAD
    helm:
      releaseName: python-rest-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: app-test
