name: Build Chart

on:
  push:
    branches:
      - main
 
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install helm
      run: |
        wget https://get.helm.sh/helm-v3.9.3-linux-amd64.tar.gz
        tar xvf helm-v3.9.3-linux-amd64.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin
        rm helm-v3.9.3-linux-amd64.tar.gz
        rm -rf linux-amd64
        helm version

    - name: Clone externa repository
      env:
        repository: 'https://github.com/Davidh120/python-rest-api-chart'
        branch: 'main'
      run: |
        git clone --single-branch --branch ${{ env.branch }} ${{ env.repository }} python-rest-api-chart
        cd python-rest-api-chart && rm desarrollo-0.1.0.tgz 

    - name: Delete desarrollo-0.1.0.tgz
      run: |
        find . -name 'desarrollo-0.1.0.tgz' -exec rm -f {} \;

    - name: Build chart and index file
      run: |
        cd python-rest-api-chart
        helm package ..
        helm repo index . --url https://github.com/Davidh120/python-rest-api-chart.git
 
    - name: Push chart
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_REPOSITORY }}
      run: |
        cd python-rest-api-chart
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "New chart"
        git remote set-url origin https://Davidh120:${{ env.GITHUB_TOKEN }}@github.com/Davidh120/python-rest-api-chart.git
        git push origin main

        
        
